### ISSUE TITLE
self.metrics moved to torchmetrics

### ISSUE THREAD

**Issue by m-ali-awan** [PacktPublishing/Deep-Learning-with-PyTorch-Lightning#2]
self.metrics is giving error, and now we have to install torchmetrics:

```
pip install torchmetrics
```

and then specifically import metric like:
```
accur=torchmetrics.Accuracy()
accuracy=accur(outputs,labels)
```

**Comment by kunal-savvy** [comment]
Thanks for pointing it out.its a new change in the latest PL version. Taken a note.

**Comment by kunal-savvy** [comment]
This is being fixed in the updated code for the revised edition.

**Comment by Borda** [comment]
just curious, does the book mention which PL version it is compatible with because the `torchmetrics` were moved out as an independent package about a year ago and since then deprecated in PL itself...

**Comment by kunal-savvy** [comment]
@Borda yes, for every chapter the version of PL is being mentioned in the Tech Req section of the book.  Since this chapter was one of the earliest written with older version of PL it had legacy code. We are updating most of the chapters to latest (1.5.x) version in the revised edition and should take care these depreciation.

**Comment by kunal-savvy** [comment]
@m-ali-awan @Borda 

Dear Reader 


Thanks a lot for showing your interest and trust in the book. I want to profusely apologize for the poor experience you had in the pre-release version of the book. 


To give a quick context about the background; we have started & finalized the draft on PyTorch Lightning version 1.1.x or 1.0.x. However as we neared the launch, it became clear that with the PyTorch Lightning 1.5.x release, a lot of framework has undergone functional changes including callbacks & key capabilities. While the code could have worked in isolation by installing correct packages; in order to have better experience for the readers, we have decided to delay the release and upgrade all the content to 1.5.x and release a revised edition. This is to ensure that all the latest features of new framework releases are correctly captured which makes applications in Deep Learning even easier.


To this effect we have changed the release date for the book in the USA on Amazon. The book was not released in the USA during this time.However, somehow that change was  not reflected in some countries and pre-orders were released for the previous version of the book. Neither me nor the publisher were aware of this. We came to know of this only after feedback from users like you, which we could not fully understand at first since we were not aware of anyone actively using either the book or the Github repo.  The Github code files during this time continued to evolve to reflect our upgrade. I am sorry that you had a bad experience due to this.


Nevertheless, the updated version is ready and it is more than just a code upgrade to PL 1.5.x

   - It has all new revised use cases with larger, more complex real-world datasets to help you learn better
   -  A new chapter is added on Lightning Flash for SOTA models
    - New content with examples on video classification, automatic speech recognition, Transfer learning on ResNet-50 as well as BERT NLP
    - A revamped structure to easily ensure packaged compatibility during the installation process
    - A section on the next steps to advance your learning in each chapter


We must thank you for initial feedback as well on install instructions which we tried to address with more depth. 


Me and Publisher would be happy to send you a free revised copy as a replacement for your previous order if received before April release. Doing so directly via Amazon turned out to be a challenge since Amazon does not share customer data.  If you can forward your order info along with your contact details to the publisher email id at [Gebin George](mailto:gebing@packt.com); then we would be glad to send the copy of revised edition. 


My sincere apologies again for the confusion and hope that you will give another chance to trust us. As always we appreciate your feedback, so please do share if you come across any new issues. You can always reach me at kunal.sawarkar@gmail.com.


Thanks & Regards,
Kunal S
