### ISSUE TITLE
Chapter 2: Perceptron_model_XOR.ipynb 

### ISSUE THREAD

**Issue by theja-vanka** [PacktPublishing/Deep-Learning-with-PyTorch-Lightning#3]
When reproducing the same code as is from repository. I am facing the following issue.

ValueError: too many values to unpack (expected 2)

torch version: 1.10.1
pytorch ligthening version: 1.5.6

**Comment by kunal-savvy** [comment]
The technical req section does not seem to be followed in this case. Code from repository is to be used only after reading the book instructions on how to use it. Refer to technical requirements sections for mode details

**Comment by theja-vanka** [comment]
I have noticed that you have removed all the notebooks post my comment. Are you planing to upload the fixed version of the code to your repository again.

**Comment by Psiopteryx** [comment]
Same error. Incidentally torch 1.7.1 is not available on later versions of Python (Mac) even with downgrading. Tried on linux with pytorch_lightning 1.2.3, Torch 1.7.1 as per specs same error.

**Comment by theja-vanka** [comment]
I am very disappointed by the author. He not only changes my issue's content but also doesn't admit his mistakes. A lot of mistakes in book and I had to google and read PyTorch_lightning documentation in-order to fix things.

Note to author: Mistakes happen but fixing them over suppressing them takes priority. Be humble.

**Comment by kunal-savvy** [comment]
The code is correct in the book. Please refer to it. Your comments proves that you have not yet read the book(which is not yet released).

**Comment by Psiopteryx** [comment]
Your book was released in Amazon.fr and I have it. Please see attached.
Certain portions of Ch1 work with Mac OS but not Linux even with the exact
packages mentioned in it. Would love to see code up on GitHub as can’t work
through the book without it.

**Comment by kunal-savvy** [comment]
Let me check with the publisher and revert back on the same.  In case you have it, we will make sure that you get the free copy of revised edition (It would have code updated to work on 1.5.x  version of Pytorch Lightning along with covering new features)

**Comment by Psiopteryx** [comment]
Thank you!

**Comment by kunal-savvy** [comment]
@Psiopteryx @theja-vanka 
Dear Reader 


Thanks a lot for showing your interest and trust in the book. I want to profusely apologize for the poor experience you had in the pre-release version of the book. 


To give a quick context about the background; we have started & finalized the draft on PyTorch Lightning version 1.1.x or 1.0.x. However as we neared the launch, it became clear that with the PyTorch Lightning 1.5.x release, a lot of framework has undergone functional changes including callbacks & key capabilities. While the code could have worked in isolation by installing correct packages; in order to have better experience for the readers, we have decided to delay the release and upgrade all the content to 1.5.x and release a revised edition. This is to ensure that all the latest features of new framework releases are correctly captured which makes applications in Deep Learning even easier.


To this effect we have changed the release date for the book in the USA on Amazon. The book was not released in the USA during this time.However, somehow that change was  not reflected in some countries and pre-orders were released for the previous version of the book. Neither me nor the publisher were aware of this. We came to know of this only after feedback from users like you, which we could not fully understand at first since we were not aware of anyone actively using either the book or the Github repo.  The Github code files during this time continued to evolve to reflect our upgrade. I am sorry that you had a bad experience due to this.


Nevertheless, the updated version is ready and it is more than just a code upgrade to PL 1.5.x

   - It has all new revised use cases with larger, more complex real-world datasets to help you learn better
   -  A new chapter is added on Lightning Flash for SOTA models
    - New content with examples on video classification, automatic speech recognition, Transfer learning on ResNet-50 as well as BERT NLP
    - A revamped structure to easily ensure packaged compatibility during the installation process
    - A section on the next steps to advance your learning in each chapter


We must thank you for initial feedback as well on install instructions which we tried to address with more depth. 


Me and Publisher would be happy to send you a free revised copy as a replacement for your previous order if received before April release. Doing so directly via Amazon turned out to be a challenge since Amazon does not share customer data.  If you can forward your order info along with your contact details to the publisher email id at [Gebin George](mailto:gebing@packt.com); then we would be glad to send the copy of revised edition. 


My sincere apologies again for the confusion and hope that you will give another chance to trust us. As always we appreciate your feedback, so please do share if you come across any new issues. You can always reach me at kunal.sawarkar@gmail.com.


Thanks & Regards,
Kunal S

**Comment by Psiopteryx** [comment]
Thank you Kumal, and thanks for handling it well and revising. I've
contacted the publisher for the new book and can't wait to work through it,

Kind regards,
Philip
